# Generated by Django 3.2 on 2021-04-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidates',
            table='candidates',
        ),
    ]
