# Generated by Django 3.2 on 2021-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudl', '0002_alter_candidates_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='placed',
            field=models.CharField(default='Nil', max_length=50),
        ),
    ]
