# Generated by Django 3.2 on 2021-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudl', '0004_auto_20210416_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('required', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('package', models.FloatField()),
                ('taken', models.IntegerField()),
                ('whom', models.TextField()),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
